checkpoint: "facebook/wav2vec2-large-960h"

onnx_parameters:
  export_params: True
  opset_version: 14
  do_constant_folding: True
  input_names: ["input"]
  output_names: ["output"]
  dynamic_axes: {"input": {1: "audio_len"}, "output": {1: "audio_len"}}

output:
  onnx: "output/models/wav2vec2-large-960h.onnx"
  quantized: "output/models/wav2vec2-large-960h.quant.onnx"

# sqlite3_database:
#   path: 'voice_validation.db'